
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
    ---@class AudioType
     ---@field public UNKNOWN integer
     ---@field public ACC integer
     ---@field public AIFF integer
    ['AudioType'] = {   UNKNOWN=0,  ACC=1,  AIFF=2,  };
    ---@class common.EBoolOperator
     ---@field public AND integer
     ---@field public OR integer
    ['common.EBoolOperator'] = {   AND=0,  OR=1,  };
    ---@class common.EProfessionType @职业
     ---@field public WARRIOR integer @战士
     ---@field public MAGE integer @法师
     ---@field public ASSASSIN integer @刺客
    ['common.EProfessionType'] = {   WARRIOR=1,  MAGE=2,  ASSASSIN=3,  };
    ---@class common.ERaceType @种族
     ---@field public HUMAN integer @人族
     ---@field public ORC integer @魔族
    ['common.ERaceType'] = {   HUMAN=1,  ORC=2,  };
    ---@class dialog.ESpeakerType @对话发言者
     ---@field public CHARACTER integer @玩家角色
     ---@field public NPC integer @npc
    ['dialog.ESpeakerType'] = {   CHARACTER=1,  NPC=2,  };
    ---@class item.ECurrencyType
     ---@field public DIAMOND integer @钻石
     ---@field public GOLD integer @金币
     ---@field public EXP integer @经验
     ---@field public CRYSTAL integer @水晶
    ['item.ECurrencyType'] = {   DIAMOND=1,  GOLD=2,  EXP=3,  CRYSTAL=4,  };
    ---@class item.EEquipmentQuality @道具品质
     ---@field public WHITE integer @白
     ---@field public GREEN integer @绿
     ---@field public BLUE integer @蓝
     ---@field public PURPLE integer @紫
     ---@field public GOLDEN integer @金
    ['item.EEquipmentQuality'] = {   WHITE=0,  GREEN=1,  BLUE=2,  PURPLE=3,  GOLDEN=4,  };
    ---@class item.EEquipmentStarQualityType
     ---@field public ONE integer @一星
     ---@field public TWO integer @二星
     ---@field public THREE integer @三星
     ---@field public FOUR integer @四星
     ---@field public FIVE integer @五星
     ---@field public SIX integer @六星
     ---@field public SEVEN integer @七星
     ---@field public EIGHT integer @八星
     ---@field public NINE integer @九星
     ---@field public TEN integer @十星
    ['item.EEquipmentStarQualityType'] = {   ONE=1,  TWO=2,  THREE=3,  FOUR=4,  FIVE=5,  SIX=6,  SEVEN=7,  EIGHT=8,  NINE=9,  TEN=10,  };
    ---@class item.EMajorType
     ---@field public CURRENCY integer @货币
     ---@field public EQUIPMENT integer @装备
     ---@field public QUEST integer @任务
     ---@field public TREASURE_BOX integer @宝箱
    ['item.EMajorType'] = {   CURRENCY=1,  EQUIPMENT=2,  QUEST=3,  TREASURE_BOX=4,  };
    ---@class item.EMinorType
     ---@field public DIAMOND integer @钻石
     ---@field public GOLD integer @金币
     ---@field public EXP integer @经验
     ---@field public CRYSTAL integer @水晶
     ---@field public COAT integer @外套
     ---@field public UPPER_JACKET integer @上衣
     ---@field public TROUSERS integer @裤子
     ---@field public SHOES integer @鞋子
     ---@field public HAT integer @帽子
     ---@field public GLOVE integer @手套
     ---@field public QUEST integer @任务道具
    ['item.EMinorType'] = {   DIAMOND=101,  GOLD=102,  EXP=103,  CRYSTAL=104,  COAT=220,  UPPER_JACKET=230,  TROUSERS=241,  SHOES=260,  HAT=272,  GLOVE=277,  QUEST=301,  };
    ---@class item.EUseType
     ---@field public MANUAL integer @手动
     ---@field public AUTO integer @自动
    ['item.EUseType'] = {   MANUAL=0,  AUTO=1,  };
}

local beans = {}
    do
    ---@class common.DateTimeRange 
     ---@field public start_time integer
     ---@field public end_time integer
        local class = {
            { name='start_time', type='integer'},
            { name='end_time', type='integer'},
        }
        beans['common.DateTimeRange'] = class
    end
    do
    ---@class common.FloatRange 
     ---@field public min number
     ---@field public max number
        local class = {
            { name='min', type='number'},
            { name='max', type='number'},
        }
        beans['common.FloatRange'] = class
    end
    do
    ---@class common.IntRange 
     ---@field public min integer
     ---@field public max integer
        local class = {
            { name='min', type='integer'},
            { name='max', type='integer'},
        }
        beans['common.IntRange'] = class
    end
    do
    ---@class common.OneDayTimeRange 
     ---@field public start_time common.TimeOfDay
     ---@field public end_time common.TimeOfDay
        local class = {
            { name='start_time', type='common.TimeOfDay'},
            { name='end_time', type='common.TimeOfDay'},
        }
        beans['common.OneDayTimeRange'] = class
    end
    do
    ---@class common.ProfessionAttribute  @职业属性
     ---@field public healthMax integer @生命上限
        local class = {
            { name='healthMax', type='integer'},
        }
        beans['common.ProfessionAttribute'] = class
    end
    do
    ---@class common.RaceAttribute  @种族属性
     ---@field public strength integer @力量
     ---@field public stamina integer @耐力
        local class = {
            { name='strength', type='integer'},
            { name='stamina', type='integer'},
        }
        beans['common.RaceAttribute'] = class
    end
    do
    ---@class common.TimeOfDay 
     ---@field public hour integer
     ---@field public minute integer
     ---@field public second integer
        local class = {
            { name='hour', type='integer'},
            { name='minute', type='integer'},
            { name='second', type='integer'},
        }
        beans['common.TimeOfDay'] = class
    end
    do
    ---@class config.TbGlobalConfig 
     ---@field public mainCityMapId integer @参数1
     ---@field public playerPrefabCity string @道具
     ---@field public x3 integer
     ---@field public x4 integer
     ---@field public x5 integer
     ---@field public x6 integer
     ---@field public x7 integer[]
        local class = {
            { name='mainCityMapId', type='integer'},
            { name='playerPrefabCity', type='string'},
            { name='x3', type='integer'},
            { name='x4', type='integer'},
            { name='x5', type='integer'},
            { name='x6', type='integer'},
            { name='x7', type='integer[]'},
        }
        beans['config.TbGlobalConfig'] = class
    end
    do
    ---@class config.TbGuide 
     ---@field public id integer
     ---@field public npcId integer
     ---@field public dilogs dialog.Dialog[] @对话列表
     ---@field public act_id integer @动作id
     ---@field public coin integer @金币数量
     ---@field public exp integer @经验数量
        local class = {
            { name='id', type='integer'},
            { name='npcId', type='integer'},
            { name='dilogs', type='dialog.Dialog[]'},
            { name='act_id', type='integer'},
            { name='coin', type='integer'},
            { name='exp', type='integer'},
        }
        beans['config.TbGuide'] = class
    end
    do
    ---@class config.TbMap 
     ---@field public id integer
     ---@field public mapName string @地图名称
     ---@field public sceneName string @场景名称
     ---@field public power integer
     ---@field public mainCameraPos vec3 @主摄像机位置
     ---@field public mainCameraRote vec3 @主摄像机旋转
     ---@field public playerBornPos vec3 @玩家出生位置
     ---@field public playerBornRota vec3 @玩家出生旋转
     ---@field public bbox rect2 @地图
     ---@field public aoiRadius number @aoi半径
     ---@field public monsterPositions string[] @怪物刷新点
     ---@field public exp integer @掉落经验
     ---@field public coin integer @掉落金币
     ---@field public crystal integer @掉落水晶
        local class = {
            { name='id', type='integer'},
            { name='mapName', type='string'},
            { name='sceneName', type='string'},
            { name='power', type='integer'},
            { name='mainCameraPos', type='vec3'},
            { name='mainCameraRote', type='vec3'},
            { name='playerBornPos', type='vec3'},
            { name='playerBornRota', type='vec3'},
            { name='bbox', type='rect2'},
            { name='aoiRadius', type='number'},
            { name='monsterPositions', type='string[]'},
            { name='exp', type='integer'},
            { name='coin', type='integer'},
            { name='crystal', type='integer'},
        }
        beans['config.TbMap'] = class
    end
    do
    ---@class config.TbMonster 
     ---@field public id integer
     ---@field public monsterName string @名称
     ---@field public monsterType integer @类型
     ---@field public isStop boolean
     ---@field public resPath string @资源地址
     ---@field public skillId integer @技能id
     ---@field public attackDistance number @攻击距离
     ---@field public health integer @生命上限
     ---@field public physicalAttack integer @物理攻击
     ---@field public magicAttack integer @魔法伤害
     ---@field public physicalDefense integer @物理防御
     ---@field public magicDefense integer @魔法防御
     ---@field public dodge integer @闪避
     ---@field public penetration integer @穿透
     ---@field public critical integer @暴击
        local class = {
            { name='id', type='integer'},
            { name='monsterName', type='string'},
            { name='monsterType', type='integer'},
            { name='isStop', type='boolean'},
            { name='resPath', type='string'},
            { name='skillId', type='integer'},
            { name='attackDistance', type='number'},
            { name='health', type='integer'},
            { name='physicalAttack', type='integer'},
            { name='magicAttack', type='integer'},
            { name='physicalDefense', type='integer'},
            { name='magicDefense', type='integer'},
            { name='dodge', type='integer'},
            { name='penetration', type='integer'},
            { name='critical', type='integer'},
        }
        beans['config.TbMonster'] = class
    end
    do
    ---@class config.TbProfessionLevel 
     ---@field public profession integer @职业
     ---@field public attribute table<integer,common.ProfessionAttribute>
        local class = {
            { name='profession', type='integer'},
            { name='attribute', type='table<integer,common.ProfessionAttribute>'},
        }
        beans['config.TbProfessionLevel'] = class
    end
    do
    ---@class config.TbRaceLevel 
     ---@field public race integer @种族
     ---@field public attribute table<integer,common.RaceAttribute>
        local class = {
            { name='race', type='integer'},
            { name='attribute', type='table<integer,common.RaceAttribute>'},
        }
        beans['config.TbRaceLevel'] = class
    end
    do
    ---@class config.TbRdnameGivenNameFemale 
     ---@field public id integer
     ---@field public name string @内容
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
        }
        beans['config.TbRdnameGivenNameFemale'] = class
    end
    do
    ---@class config.TbRdnameGivenNameMale 
     ---@field public id integer
     ---@field public name string @内容
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
        }
        beans['config.TbRdnameGivenNameMale'] = class
    end
    do
    ---@class config.TbRdnameSurname 
     ---@field public id integer
     ---@field public name string @内容
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
        }
        beans['config.TbRdnameSurname'] = class
    end
    do
    ---@class config.TbSkill 
     ---@field public id integer
     ---@field public skillName string @技能名称
     ---@field public coolDownTime integer @cd时间(毫秒)
     ---@field public duration integer @技能持续时间(毫秒)
     ---@field public animationAction integer @动画动作
     ---@field public fx string @音效
     ---@field public isCombo boolean @是否连击
     ---@field public isCollide boolean @抵抗？
     ---@field public isBreak boolean @是否打断
     ---@field public damageType integer @伤害类型
     ---@field public moveList integer[] @技能移动列表
     ---@field public actionList integer[] @技能动作列表
     ---@field public damageList integer[] @技能伤害列表
        local class = {
            { name='id', type='integer'},
            { name='skillName', type='string'},
            { name='coolDownTime', type='integer'},
            { name='duration', type='integer'},
            { name='animationAction', type='integer'},
            { name='fx', type='string'},
            { name='isCombo', type='boolean'},
            { name='isCollide', type='boolean'},
            { name='isBreak', type='boolean'},
            { name='damageType', type='integer'},
            { name='moveList', type='integer[]'},
            { name='actionList', type='integer[]'},
            { name='damageList', type='integer[]'},
        }
        beans['config.TbSkill'] = class
    end
    do
    ---@class config.TbSkillAction 
     ---@field public id integer
     ---@field public delayTime integer @延迟时间(毫秒)
     ---@field public radius number @半径
     ---@field public angle integer @角度
        local class = {
            { name='id', type='integer'},
            { name='delayTime', type='integer'},
            { name='radius', type='number'},
            { name='angle', type='integer'},
        }
        beans['config.TbSkillAction'] = class
    end
    do
    ---@class config.TbSkillMove 
     ---@field public id integer
     ---@field public delayTime integer @延迟时间(毫秒)
     ---@field public moveTime integer @移动时间(毫秒)
     ---@field public moveDistance number @移动距离
        local class = {
            { name='id', type='integer'},
            { name='delayTime', type='integer'},
            { name='moveTime', type='integer'},
            { name='moveDistance', type='number'},
        }
        beans['config.TbSkillMove'] = class
    end
    do
    ---@class config.TbTaskReward 
     ---@field public id integer
     ---@field public taskName string @任务名称
     ---@field public count integer @数量
     ---@field public exp integer @经验
     ---@field public coin integer @金币
        local class = {
            { name='id', type='integer'},
            { name='taskName', type='string'},
            { name='count', type='integer'},
            { name='exp', type='integer'},
            { name='coin', type='integer'},
        }
        beans['config.TbTaskReward'] = class
    end
    do
    ---@class config.TbTaskStrong 
     ---@field public id integer
     ---@field public pos integer @部位
     ---@field public starLevel integer @星级
     ---@field public addhp integer @增加生命值
     ---@field public addDamage integer @增加伤害
     ---@field public addDefense integer @增加防御
     ---@field public minLevel integer @最小等级
     ---@field public coin integer @金币
     ---@field public crystal integer @水晶
        local class = {
            { name='id', type='integer'},
            { name='pos', type='integer'},
            { name='starLevel', type='integer'},
            { name='addhp', type='integer'},
            { name='addDamage', type='integer'},
            { name='addDefense', type='integer'},
            { name='minLevel', type='integer'},
            { name='coin', type='integer'},
            { name='crystal', type='integer'},
        }
        beans['config.TbTaskStrong'] = class
    end
    do
    ---@class dialog.Dialog  @对话
     ---@field public speaker integer @发言者
     ---@field public content string @对话内容
        local class = {
            { name='speaker', type='integer'},
            { name='content', type='string'},
        }
        beans['dialog.Dialog'] = class
    end
    do
    ---@class item.Item  @道具
     ---@field public id integer @道具id
     ---@field public name string
     ---@field public major_type integer
     ---@field public minor_type integer
     ---@field public max_pile_num integer
     ---@field public quality integer
     ---@field public icon string
     ---@field public icon_backgroud string
     ---@field public icon_mask string
     ---@field public desc string
     ---@field public show_order integer
        local class = {
            { name='id', type='integer'},
            { name='name', type='string'},
            { name='major_type', type='integer'},
            { name='minor_type', type='integer'},
            { name='max_pile_num', type='integer'},
            { name='quality', type='integer'},
            { name='icon', type='string'},
            { name='icon_backgroud', type='string'},
            { name='icon_mask', type='string'},
            { name='desc', type='string'},
            { name='show_order', type='integer'},
        }
        beans['item.Item'] = class
    end
    do
    ---@class rect2 
     ---@field public center vec2
     ---@field public extents vec2
        local class = {
            { name='center', type='vec2'},
            { name='extents', type='vec2'},
        }
        beans['rect2'] = class
    end
    do
    ---@class vec2 
     ---@field public x number
     ---@field public y number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
        }
        beans['vec2'] = class
    end
    do
    ---@class vec3 
     ---@field public x number
     ---@field public y number
     ---@field public z number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
            { name='z', type='number'},
        }
        beans['vec3'] = class
    end
    do
    ---@class vec4 
     ---@field public x number
     ---@field public y number
     ---@field public z number
     ---@field public w number
        local class = {
            { name='x', type='number'},
            { name='y', type='number'},
            { name='z', type='number'},
            { name='w', type='number'},
        }
        beans['vec4'] = class
    end

local tables =
{
    { name='GlobalConfig', file='config_globalconfig', mode='one', value_type='config.TbGlobalConfig'},
    { name='Guide', file='config_guide', mode='map', index='id', value_type='config.TbGuide' },
    { name='Skill', file='config_skill', mode='map', index='id', value_type='config.TbSkill' },
    { name='SkillAction', file='config_skillaction', mode='map', index='id', value_type='config.TbSkillAction' },
    { name='SkillMove', file='config_skillmove', mode='map', index='id', value_type='config.TbSkillMove' },
    { name='TaskStrong', file='config_taskstrong', mode='map', index='id', value_type='config.TbTaskStrong' },
    { name='TaskReward', file='config_taskreward', mode='map', index='id', value_type='config.TbTaskReward' },
    { name='Map', file='config_map', mode='map', index='id', value_type='config.TbMap' },
    { name='Monster', file='config_monster', mode='map', index='id', value_type='config.TbMonster' },
    { name='RdnameGivenNameFemale', file='config_rdnamegivennamefemale', mode='list', index='id', value_type='config.TbRdnameGivenNameFemale' },
    { name='RdnameGivenNameMale', file='config_rdnamegivennamemale', mode='list', index='id', value_type='config.TbRdnameGivenNameMale' },
    { name='RdnameSurname', file='config_rdnamesurname', mode='list', index='id', value_type='config.TbRdnameSurname' },
    { name='RaceLevel', file='config_racelevel', mode='map', index='race', value_type='config.TbRaceLevel' },
    { name='ProfessionLevel', file='config_professionlevel', mode='map', index='profession', value_type='config.TbProfessionLevel' },
}

return { enums = enums, beans = beans, tables = tables }

